config/routes.rb
Reading::Engine.routes.draw do


  scope '/:locale' do
    get 'pages/:id/*name', to: 'pages#show', as: :page

    resources :notes, except: [:show] do
      collection do
        get 'hot'
        get 'latest'
      end
    end

    resources :books, only: [:index, :show, :destroy] do
      collection do
        get 'hot'
      end
    end

    resources :favorites, only: [:index, :create, :destroy]
  end

  root 'books#hot'
end

app/models/reading/application_record.rb
module Reading
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/reading/book.rb
module Reading
  class Book < ApplicationRecord
    validates :author, :publisher, :title, :version, :lang, :subject, :published_at, presence: true

    has_many :notes, class_name: 'Reading::Note', foreign_key: 'reading_book_id'
  end
end

app/models/reading/favorite.rb
module Reading
  class Favorite < ApplicationRecord
    validates :title, :href, presence: true
    validates :href, uniqueness: { scope: :user_id}

    belongs_to :user
  end
end

app/models/reading/note.rb
module Reading
  class Note < ApplicationRecord
    validates :body, presence: true
    belongs_to :book, class_name: 'Reading::Book', foreign_key: 'reading_book_id'

    belongs_to :user
  end
end

app/controllers/reading/application_controller.rb
module Reading
  class ApplicationController < ActionController::Base
    include Pundit
    protect_from_forgery with: :exception

    before_action :set_locale
    layout 'application'

    def default_url_options
      { locale: I18n.locale }
    end

    protected
    def set_locale
      I18n.locale = params[:locale] || browser.accept_language.first.full
    end

  end
end

app/controllers/reading/books_controller.rb
require_dependency 'reading/application_controller'
require 'epub/parser'

module Reading
  class BooksController < ApplicationController

    def hot
      @books = Book.order(vote: :desc).page params[:page]
    end

    def index
      authorize Book.new
      @books = Book.order(updated_at: :desc).page params[:page]
      render layout: 'dashboard'
    end

    def destroy
      bk = Book.find(params[:id])
      authorize bk
      bk.destroy

      redirect_to books_path
    end


    def show
      @book = Book.find(params[:id])
      bk = EPUB::Parser.parse @book.file
      bk.each_content do |pg|
        if pg.id == 'toc'
          redirect_to page_path(id:@book.id, name:pg.entry_name)
          return
        end
      end
      head :not_found
    end
  end
end

app/controllers/reading/favorites_controller.rb
require_dependency 'reading/application_controller'

module Reading
  class FavoritesController < ApplicationController

    def index
      authorize Reading::Favorite.new
      render layout: 'dashboard'
    end

    def create
      fav = Reading::Favorite.new params.permit(:title, :href)
      authorize fav
      fav.user = current_user
      fav.save
      if fav.valid?
        flash[:notice] = ''
      else
        flash[:alert] = fav.errors.inspect
      end
      redirect_to fav.href
    end


    def destroy
      fav = Reading::Favorite.find(params[:id])
      authorize fav

      fav.destroy
      redirect_to favorites_path
    end

  end

end

app/controllers/reading/notes_controller.rb
require_dependency 'reading/application_controller'

module Reading
  class NotesController < ApplicationController
    before_action :authenticate_user!, except: [:hot, :latest]

    def new
      @note = Note.new reading_book_id: params[:book_id]
      authorize @note
    end

    def create
      @note = Note.new params.require(:note).permit(:body, :reading_book_id)
      authorize @note
      @note.user = current_user

      if @note.save
        redirect_to latest_notes_path
      else
        render 'new'
      end
    end


    def edit
      @note = Note.find(params[:id])
      authorize @note
    end

    def update
      @note = Note.find(params[:id])
      authorize @note
      if @note.update(params.require(:note).permit(:body))
        redirect_to latest_notes_path
      else
        render 'edit'
      end

    end

    def destroy
      n = Note.find(params[:id])
      authorize @note

      n.destroy
      redirect_to notes_path
    end


    def index
      if current_user.is_admin?
        @notes = Note.order(updated_at: :desc).page params[:page]
      else
        @notes = Note.where(user_id: current_user.id).order(updated_at: :desc).page params[:page]
      end
      render layout: 'dashboard'
    end

    def hot
      @notes = Note.order(updated_at: :desc).page params[:page]
      @title = t '.title'
      render 'list'
    end

    def latest
      @notes = Note.order(vote: :desc).page params[:page]
      @title = t '.title'
      render 'list'
    end
  end
end

app/controllers/reading/pages_controller.rb
require_dependency 'reading/application_controller'

module Reading
  class PagesController < ApplicationController
    def show
      @book = Book.find(params[:id])
      bk = EPUB::Parser.parse @book.file

      name = "#{params[:name]}.#{params[:format]}"
      bk.each_content do |pg|
        if pg.entry_name == name
          case pg.media_type
          when 'application/xhtml+xml'
            doc =Nokogiri::XML(pg.read)
            @title = "#{doc.css('head title').first.content}-#{@book.title}-#{@book.author}"
            @body = doc.css('body').first.inner_html
          else
            send_data pg.read, type: pg.media_type, disposition: 'inline'
          end
          return
        end
      end
      head :not_found
    end
  end
end

app/helpers/reading/application_helper.rb
module Reading
  module ApplicationHelper
  end
end

app/views/layouts/reading/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reading</title>
  <%= stylesheet_link_tag    "reading/application", media: "all" %>
  <%= javascript_include_tag "reading/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reading/books/hot.html.slim
h2
  = @title = t '.title'
hr
= paginate @books, theme: 'twitter-bootstrap-4'

div class="row"
  -@books.each do |i|
    div class="col-md-4"
      div class="card"
        div class="card-block"
          h4 class="card-title"
            = link_to i.title, book_path(i)
          p class="card-text" #{i.author} #{i.subject}
          = link_to t('buttons.view'), book_path(i), class: 'btn btn-secondary'

app/views/reading/books/index.html.slim
h2
  = @title = t '.title'
hr
= paginate @books, theme: 'twitter-bootstrap-4'

table class="table table-bordered table-hover"
  thead
    tr
      th #{t 'activerecord.attributes.reading/book.updated_at'}
      th #{t 'activerecord.attributes.reading/book.title'}
      th #{t 'activerecord.attributes.reading/book.author'}
      th #{t 'activerecord.attributes.reading/book.publisher'}
      th #{t 'activerecord.attributes.reading/book.subject'}
      th #{t 'buttons.manage'}
  tbody
    - @books.each do |i|
      tr
        th scope="row" #{time_ago_in_words i.updated_at}
        td
          = link_to i.title, book_path(i), target: :_blank
        td #{i.author}
        td #{i.publisher}
        td #{i.subject}
        td
          = render 'shared/btn-remove', url: book_path(i)

app/views/reading/favorites/index.html.slim
h2
  = @title = t '.title'
hr
ul class="list-group"
  - Reading::Favorite.where(user_id: current_user.id).order(id: :desc).each do |i|
    li class="list-group-item"
      = link_to i.title, i.href, target: :_blank
      | &nbsp;
      = link_to t('buttons.remove'), favorite_path(i), method: :delete, data: { confirm: t('messages.are_you_sure')}, class: 'btn btn-danger btn-sm'

app/views/reading/notes/edit.html.slim
h2
  = @title = t '.title', id: @note.id
hr
= simple_form_for @note do |f|
  = f.input :body, as: :text
  = f.button :submit, t('buttons.submit')
  = render 'shared/btn-remove', note_path(@note)

app/views/reading/notes/index.html.slim
h2
  = @title = t '.title'
hr
= paginate @notes, theme: 'twitter-bootstrap-4'

table class="table table-bordered table-hover"
  thead
    tr
      th #{t 'activerecord.attributes.reading/note.updated_at'}
      th #{t 'activerecord.attributes.reading/note.body'}
      th #{t 'buttons.manage'}
  tbody
    - @notes.each do |i|
      tr
        th scope="row" #{time_ago_in_words i.updated_at}
        td #{i.body}
        td
          = render 'shared/btn-remove', url: note_path(i)

app/views/reading/notes/list.html.slim
h2
  = @title
hr
= paginate @notes, theme: 'twitter-bootstrap-4'

div class="row"
  -@notes.each do |i|
    div class="col-md-4"
      div class="card"
        div class="card-block"
          p class="card-text" #{i.body}
          = link_to t('buttons.view'), book_path(i.book), class: 'btn btn-secondary'

app/views/reading/notes/new.html.slim
h2
  = @title = t '.title'
hr
= simple_form_for @note do |f|
  = f.input :reading_book_id, as: :hidden
  = f.input :body, as: :text
  = f.button :submit, t('buttons.submit')

app/views/reading/pages/show.html.slim
div class="row"
  div class="col-md-9" #{raw @body}
  div class="col-md-3"
    h4
      = t '.notes'
      - if user_signed_in?
        = link_to t('buttons.new'), new_note_path(book_id: @book.id), class:'btn btn-link'
        = link_to t('buttons.favorite'), favorites_path(title: @book.title, href:book_path(@book)), method: :post, class:'btn btn-link'
    hr
    - @book.notes.order(updated_at: :desc).each do |i|
      blockquote class="blockquote"
        p class="mb-0" #{i.body}
        footer class="blockquote-footer" #{time_ago_in_words i.updated_at}